FROM mysql:8.0

# Potentially override startup scripts or configuration here.
# WARNING: Allowing an empty root password is insecure!
ENV MYSQL_ROOT_PASSWORD=""
ENV MYSQL_DATABASE=loading

EXPOSE 3306
